name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Gradle dependencies (warm cache)
        run: ./gradlew --no-daemon --stacktrace dependencies || true

      - name: Build & unit test (debug only)
        run: ./gradlew --no-daemon --stacktrace clean testDebugUnitTest assembleDebug

      - name: Assemble Release (manual only)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: ./gradlew --no-daemon --stacktrace assembleRelease

      - name: Upload APK/AAB and test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: |
            **/build/outputs/apk/**/*.apk
            **/build/outputs/bundle/**/*.aab
            **/build/reports/tests/testDebugUnitTest/*
