name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make Gradle wrapper executable (Linux/Mac)
        run: chmod +x ./gradlew

      - name: Build and test
        run: ./gradlew clean build testDebugUnitTest

      - name: Assemble Release (optional)
        run: ./gradlew assembleRelease
        if: ${{ github.event_name == 'push' }}

      - name: Upload APK artifacts (debug/release)
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: |
            **/build/outputs/apk/**/*.apk
            **/build/outputs/bundle/**/*.aab
